"""Wraps generated bytes in a download response. No business rules here -- same
Content-Disposition convention as estimator/exports.py.
"""
from pathlib import PurePath

from django.http import HttpResponse
from django.utils.text import slugify

from .textlist import FORMAT_LABELS

XLSX_CONTENT_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'


def xlsx_response(buffer, filename):
    response = HttpResponse(buffer.read(), content_type=XLSX_CONTENT_TYPE)
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response


def text_response(text, filename):
    response = HttpResponse(text, content_type='text/plain; charset=utf-8')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response


def textlist_filename(upload_name, text_format):
    stem = slugify(PurePath(upload_name or '').stem) or 'io-list'
    label = slugify(FORMAT_LABELS.get(text_format, '')) or 'text-list'
    return f'{stem}-{label}.xlsx'


def scl_filename(params):
    return f'io-mapping-db{params.input_db}-{params.output_db}-{params.hmi_io_db}.txt'
